openapi: 3.0.0
info:
  title: Hero service API
  description: Documentation Swagger pour l'API Hero service.
  version: 0.0.1
servers:
  - url: http://localhost:3002

paths:

  /heroes:
    get:
      summary: Liste tous les héros
      responses:
        '200':
          description: Liste des héros
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hero'
    post:
      summary: Crée un nouveau héros
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateHeroRequest'
      responses:
        '201':
          description: Héros créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'

  /heroes/classes:
    get:
      summary: Liste toutes les classes de héros
      responses:
        '200':
          description: Liste des classes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Class'

  /heroes/{id}:
    get:
      summary: Récupère un héros par son ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Héros trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
        '404':
          description: Héros non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /heroes/{id}/healthPoints:
    put:
      summary: Met à jour les points de vie du héros
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                healthPoints:
                  type: integer
      responses:
        '200':
          description: Héros mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
        '404':
          description: Héros non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /heroes/{id}/healthPointsMax:
    put:
      summary: Met à jour les points de vie max du héros
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                healthPointsMax:
                  type: integer
      responses:
        '200':
          description: Héros mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
        '404':
          description: Héros non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /heroes/{id}/level:
    put:
      summary: Met à jour le niveau du héros
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                level:
                  type: integer
      responses:
        '200':
          description: Héros mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
        '404':
          description: Héros non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /heroes/{id}/attackPoints:
    put:
      summary: Met à jour les points d'attaque du héros
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                attackPoints:
                  type: integer
      responses:
        '200':
          description: Héros mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
        '404':
          description: Héros non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /heroes/{id}/inventory/add:
    post:
      summary: Ajoute un objet à l'inventaire du héros
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                quantity:
                  type: integer
      responses:
        '200':
          description: Inventaire mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
        '404':
          description: Héros non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /heroes/{id}/inventory:
    put:
      summary: Ajoute un objet à l'inventaire du héros
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                quantity:
                  type: integer
      responses:
        '200':
          description: Inventaire mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
        '404':
          description: Héros non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Récupère l'inventaire du héros
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Inventaire du héros
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        '404':
          description: Héros non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Hero:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        class:
          $ref: '#/components/schemas/Class'
        healthPoints:
          type: integer
        healthPointsMax:
          type: integer
        level:
          type: integer
        attackPoints:
          type: integer
        inventory:
          type: array
          items:
            $ref: '#/components/schemas/Item'
    CreateHeroRequest:
      type: object
      properties:
        name:
          type: string
        class:
          type: string
      required:
        - name
        - class
    Class:
      type: object
      properties:
        name:
          type: string
        healthPoints:
          type: integer
        attackPoints:
          type: integer
    Item:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        quantity:
          type: integer
    Error:
      type: object
      properties:
        error:
          type: string
 